from .fontanka import FontankaProvider
from .interfax import InterfaxProvider
from .izvestiya import IzvestiyaProvider
from .kommersant import KommersantProvider
from .lentaru import LentaruProvider
from .mbh import MBHProvider
from .mediazona import MediazonaProvider
from .meduza import MeduzaProvider
from .rbk import RBKProvider
from .ria import RiaProvider
from .rt import RussianRTProvider
from .tvrain import TVRainProvider
from .vedomosti import VedomostiProvider
